channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=24.0
- pip:
  - mlflow==3.7.0
  - cloudpickle==3.1.2
  - numpy==1.25.2
  - pandas==2.2.3
  - psutil==5.9.5
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
